### PR TITLE
fix: monday and saturday delivery not working correctly

### LINKED ISSUE #3: Zondag afleverdag voor maandag levering
Wanneer je op dit moment zondag als afleverdag instelt wordt er niets mee gedaan. kan dit ervoor zorgen dat in de checkout maandag als leverdag te zien is?

### PR DESCRIPTION
**Pull request by EdieLemoine**
Fixes #3

### CODE REVIEW

**Review by tomhooijenga — APPROVED** [review]

**Review by tomhooijenga — APPROVED** [review]

File: src/delivery-options/data/request/getCutOffTime.js [hunk 1]
```diff
@@ -0,0 +1,28 @@
+import * as CONFIG from '@/data/keys/configKeys';
+import { extraDeliveryConfig } from '@/config/extraDeliveryConfig';
+import { configBus as realConfigBus } from '@/delivery-options/config/configBus';
+
+/**
+ * Set cutoff time for a special delivery day. Returns default cutoff time if the conditions for an extra delivery day
```
Comment (alexmaat) [inline src/delivery-options/data/request/getCutOffTime.js:6]: Should this be "Get cut off time" instead of "Set"?

File: src/delivery-options/data/request/requestData.js [hunk 2]
```diff
@@ -35,6 +35,6 @@ const parametersByPlatform = {
 export function getParametersByPlatform(platform = realConfigBus.get(CONFIG.PLATFORM), configBus = realConfigBus) {
   return {
     ...parametersByPlatform[platform](configBus),
-    cutoff_time: setCutOffTime(configBus),
+    cutoff_time: getCutOffTime(configBus),
```
Comment (alexmaat) [inline src/delivery-options/data/request/requestData.js:38]: Oh, j'ai confused. Why did this need to change?

File: tests/__mocks__/modules/@myparcel/js-sdk/delivery-options/getNextDeliveryOption.js [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+    return isToday && allowedInPlatform;
+  });
+
+  if (extraDelivery) {
+    // Skip saturday or monday if its setting is not enabled.
+    if (args[`${args.platform === MYPARCEL ? 'monday' : 'saturday'}_delivery`] !== 1) {
+      return next();
+    }
+
+    // With monday delivery, for example, the dropoff day is Saturday instead of Sunday.
```
Comment (alexmaat) [inline tests/__mocks__/modules/@myparcel/js-sdk/delivery-options/getNextDeliveryOption.js:42]: As well as Monday here.

File: tests/unit/delivery-options/deliveryMoment.spec.js [hunk 4]
```diff
@@ -0,0 +1,175 @@
...
+      '2020-03-18T00:00:00.000Z',
+      '2020-03-19T00:00:00.000Z',
+      '2020-03-20T00:00:00.000Z',
+      '2020-03-21T00:00:00.000Z',
+      // sunday: disallowed
+      '2020-03-23T00:00:00.000Z',
+    ]);
+  });
+
+  it('does not show monday delivery when "allow_monday_delivery" is false', async() => {
```
Comment (alexmaat) [inline tests/unit/delivery-options/deliveryMoment.spec.js:87]: Monday again.

File: src/delivery-options/data/request/requestData.js (hunk 2 above)
Comment (EdieLemoine) [reply src/delivery-options/data/request/requestData.js:38]: It doesn't set, it gets!

File: tests/unit/delivery-options/deliveryMoment.spec.js (hunk 4 above)
Comment (EdieLemoine) [reply tests/unit/delivery-options/deliveryMoment.spec.js:87]: A common standard for Jest is keeping all test names fully lowercase. However, I haven't done that in my other files so I'll just capitalize them :)
